openapi: '3.0.2'
info:
  title: PDF Service
  version: '1.0'
servers:
  - url: https://test-api.luxuryescapes.com

paths:
  /api/pdf/gift-cards:
    post:
      parameters:
        - name: access_token
          in: cookie
          description: Required if authorisation is not provided
          required: true
          schema:
            type: string
            example: MyJwTToKeN
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currency:
                  type: string
                personalised:
                  type: object
                gift_card_value:
                  type: string
                expires_at:
                  type: string
                gift_card_code:
                  type: string
          
      responses:
        '401':
          description: Login mismatch
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: integer
                    example: 401
                  message:
                    type: string
        '200':
          description: OK

  /api/pdf/tax-invoice:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                billing_country:
                  type: string
                order_currency:
                  type: string
                customer_name:
                  type: string
                date:
                  type: string
                list:
                  type: array
                  items:
                    type: object
                    properties:
                      total_price:
                        type: number
                      description:
                        type: string
      responses:
        '200':
          description: OK

